---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        speech:
            voicebank-demand:
                directory: "hdf5s/voicebank-demand/sr=44100_ch=1/train"
                hop_seconds: 3.
        noise:
            voicebank-demand:
                directory: "hdf5s/voicebank-demand/sr=44100_ch=1/train"
                hop_seconds: 3.
    indexes: "indexes/voicebank-demand/sr=44100_ch=1/train/speech_noise.pkl"
