---
task_name: piano-symphony
train:
    input_source_types:
        - piano
        - symphony
    target_source_types: 
        - piano
    indexes_dict: "indexes/piano_symphony/sr=44100_ch=2/train/piano_symphony.pkl"
    sample_rate: 44100
    channels: 2
    segment_seconds: 3.0
    model_type: UNet
    loss_type: l1_wav
    # loss_type: l1_wav_l1_sp
    mini_data: False
    mixaudio:
        piano: 1
        symphony: 1
    augmentation:
        pitch_shift: 0
        magnitude_scale:
            lower_db: -20
            higher_db: 20
    batch_data_preprocessor: BasicBatchDataPreprocessor
    learning_rate: 1e-3
    batch_size: 16
    precision: 32
    steps_per_epoch: 10000  # Every 10000 steps is called an `epoch`.
    # evaluate_step_frequency: 10000     # Evaluate every #evaluate_step_frequency steps.
    evaluate_step_frequency: 2000     # Evaluate every #evaluate_step_frequency steps.
    save_step_frequency: 10000  # Save every #save_step_frequency steps.
    early_stop_steps: 200001
    # warm_up_steps: 1000
    # warm_up_steps: 100
    warm_up_steps: 10
    reduce_lr_steps: 15000
    random_seed: 1234
    resume_checkpoint: ""

evaluate:
    segment_seconds: 10.0
    test:
        # clean_dir: "clean_testset_wav"
        # noisy_dir: "noisy_testset_wav"
        # clean_dir: "clean_trainset_wav"
        # noisy_dir: "noisy_trainset_wav"
        evaluation_audios_dir: "evaluation_audios/piano-symphony/sr=44100_ch=2/test"
    batch_size: 1