---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        violin:
            voicebank-demand:
                directory: "hdf5s/violin_solo/sr=44100_ch=2/train"
                hop_seconds: 1.
        piano:
            voicebank-demand:
                directory: "hdf5s/piano_solo/sr=44100_ch=2/train"
                hop_seconds: 3.
    indexes: "indexes/violin_piano/sr=44100_ch=2/train/violin_piano.pkl"
