---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        speech:
            voicebank-demand:
                directory: "hdf5s/voicebank-demand/sr=44100_ch=2/train"
                hop_seconds: 0.1
                key: "speech"
        music:
            musdb18:
                directory: "hdf5s/musdb18/sr=44100_ch=2/train/full_train"
                hop_seconds: 0.1
                key: "mixture"
    indexes: "indexes/voicebank-musdb18/sr=44100_ch=2/train/voicebank-musdb18.pkl"
