---
task_name: voicebank-demand
train:
    input_source_types:
        - speech
        - noise
    target_source_types: 
        - speech
    indexes_dict: "indexes/voicebank-demand/sr=44100_ch=1/train/speech_noise.pkl"
    sample_rate: 44100
    channels: 1
    segment_seconds: 3.0
    model_type: ResUNet143_DecouplePlusInplaceABN
    loss_type: l1_wav
    mini_data: False
    mixaudio:
        speech: 1
        noise: 1
    augmentation:
        pitch_shift: 0
    learning_rate: 1e-3
    batch_size: 8
    precision: 32
    steps_per_epoch: 10000  # Every 10000 steps is called an `epoch`.
    evaluate_step_frequency: 10000     # Evaluate every #evaluate_step_frequency steps.
    save_step_frequency: 50000  # Save every #save_step_frequency steps.
    early_stop_steps: 500001
    warm_up_steps: 1000
    reduce_lr_steps: 15000
    random_seed: 1234
    resume_checkpoint: ""

evaluate:
    # train: "hdf5s/musdb18/sr=44100_ch=2/train/full_train"
    # test: "hdf5s/musdb18/sr=44100_ch=2/test"
    # segment_seconds: 30.0
    batch_size: 1