---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        piano:
            instruments_solo:
                directory: "hdf5s/piano_solo/sr=44100_ch=2/train"
                hop_seconds: 3.
        symphony:
            instruments_solo:
                directory: "hdf5s/symphony_solo/sr=44100_ch=2/train"
                hop_seconds: 1.
    indexes: "indexes/piano_symphony/sr=44100_ch=2/train/piano_symphony.pkl"
